SELECT TO_CHAR(V_PROBLEM_ALL_DATA.LAST_COMPLETED_DATE, 'YYYY_MM') AS COMPLETED_DATE_YEAR_MONTH,
  TO_CHAR(V_PROBLEM_ALL_DATA.LAST_COMPLETED_DATE, 'YYYY')         AS COMPLETED_DATE_YEAR,
  V_PROBLEM_ALL_DATA.LAST_COMPLETED_DATE,
  V_PROBLEM_ALL_DATA.PROBLEM_INVESTIGATION_ID,
  V_PROBLEM_ALL_DATA.SUMMARY,
  V_PROBLEM_ALL_DATA.PRIORITY,
  V_PROBLEM_ALL_DATA.IMPACT,
  V_PROBLEM_ALL_DATA.URGENCY,
  V_PROBLEM_ALL_DATA.SERVICE,
  V_PROBLEM_ALL_DATA.PROD_CAT1,
  V_PROBLEM_ALL_DATA.PROD_CAT2,
  V_PROBLEM_ALL_DATA.PROD_CAT4,
  V_PROBLEM_ALL_DATA.STATUS,
  V_PROBLEM_ALL_DATA.STATUS_REASON,
  V_PROBLEM_ALL_DATA.ASSIGNED_GROUP,
  V_PROBLEM_ALL_DATA.ASSIGNED_SUPPORT_ORGANIZATION,
  V_PROBLEM_ALL_DATA.COORDINATOR_GROUP,
  V_PROBLEM_ALL_DATA.COORDINATOR_SUPPORT_ORG,
  CASE
      WHEN V_PROBLEM_ALL_DATA.COORDINATOR_SUPPORT_ORG = 'ao:bmw' THEN 'Yes'
      ELSE 'No'
  END AS COORDINATED_BY_BMW,
  CASE
      WHEN V_PROBLEM_ALL_DATA.COORDINATOR_SUPPORT_ORG IN ('ao-caee:ibm','ab:ibm','mt-caee:ibm') THEN 'Yes'
      ELSE 'No'
  END AS COORDINATED_BY_PROVIDER,
  V_PROBLEM_ALL_DATA.SERVICE_DEPTGRP,
  V_PROBLEM_ALL_DATA.SUBMITTER_DEPTGRP,
  V_PROBLEM_ALL_DATA.PBI_CI,
  V_PROBLEM_ALL_DATA.INVESTIGATION_DRIVER,
  V_PROBLEM_ALL_DATA.PROBLEM_LINK,
  V_PROBLEM_ALL_DATA.PROBLEM_LOCATION,
--  V_PROBLEM_ALL_DATA.RESOLUTION,
  V_PROBLEM_ALL_DATA.VENDOR_TICKET_NUMBER,
  V_PROBLEM_ALL_DATA.CLOSED_DATE,
  V_PROBLEM_ALL_DATA.KNOWN_ERROR_CREATED_DATE,
  V_PROBLEM_ALL_DATA.SUBMIT_DATE,
--  V_PROBLEM_ALL_DATA.WORKAROUND,
  V_PROBLEM_ALL_DATA.LAST_MODIFIED_DATE,
  V_PROBLEM_ALL_DATA.WORKAROUND_DETERMINED_ON_DATE,
  V_PROBLEM_ALL_DATA.TARGET_DATE,
  V_QUAL_CONFIG_ITSM_SERVICE.MIS_3_NS  AS CONTRACT,
  V_QUAL_CONFIG_ITSM_SERVICE.MIS_5_NS  AS BUSINESS_CLUSTER,
  V_QUAL_CONFIG_ITSM_SERVICE.MIS_6_NS AS REPORTED_TOWER, 
  V_QUAL_CONFIG_ITSM_SERVICE.MIS_10_NS AS COC_DATE,
  V_PROBLEM_ALL_DATA.PROD_CAT3,
  V_QUAL_CONFIG_ITSM_SERVICE.SERVICE_DEPT_NS                                        AS SERVICE_DEPT,
  V_QUAL_CONFIG_ITSM_SERVICE.SERVICE_DEPTGRP_NS                                     AS SERVICE_DEPTGRP,
  TRUNC(V_PROBLEM_ALL_DATA.LAST_MODIFIED_DATE) -  TRUNC(V_PROBLEM_ALL_DATA.SUBMIT_DATE) + 1 AS INVESTIGATION_TIME,
  CASE V_PROBLEM_ALL_DATA.PRIORITY
      WHEN 'Critical' THEN 15
      WHEN 'High' THEN 30
      WHEN 'Low' THEN 90
  END AS INVESTIGATION_TIME_TARGET,
  CASE
      WHEN V_PROBLEM_ALL_DATA.PRIORITY = 'Critical' AND TRUNC(V_PROBLEM_ALL_DATA.LAST_MODIFIED_DATE) - TRUNC(V_PROBLEM_ALL_DATA.SUBMIT_DATE) + 1 <= 15 THEN 'passed'
      WHEN V_PROBLEM_ALL_DATA.PRIORITY = 'High' AND TRUNC(V_PROBLEM_ALL_DATA.LAST_MODIFIED_DATE) - TRUNC(V_PROBLEM_ALL_DATA.SUBMIT_DATE) + 1 <= 30 THEN 'passed'
      WHEN V_PROBLEM_ALL_DATA.PRIORITY = 'Low' AND TRUNC(V_PROBLEM_ALL_DATA.LAST_MODIFIED_DATE) - TRUNC(V_PROBLEM_ALL_DATA.SUBMIT_DATE) + 1 <= 90 THEN 'passed'
      ELSE 'missed'
  END AS INVESTIGATION_TIME_ACHIEVED,
  CASE
      WHEN TO_DATE(V_QUAL_CONFIG_ITSM_SERVICE.MIS_10_NS, 'DD.MM.YY') is NULL then 'Current'
      WHEN TO_DATE(V_QUAL_CONFIG_ITSM_SERVICE.MIS_10_NS, 'DD.MM.YY') <= V_PROBLEM_ALL_DATA."SUBMIT_DATE" then 'Current'
      ELSE 'Planned'
  END COC_STATUS
FROM  "QQITSMREP_READ"."V_PROBLEM_ALL_DATA" V_PROBLEM_ALL_DATA
    left  join
      "QQITSMREP"."V_QUAL_CONFIG_ITSM_SERVICE" V_QUAL_CONFIG_ITSM_SERVICE
    on
      V_PROBLEM_ALL_DATA."SERVICE" = V_QUAL_CONFIG_ITSM_SERVICE."ITSM_SERVICE"
WHERE
     V_PROBLEM_ALL_DATA.STATUS IN ('Draft','Under Review','Request For Authorization','Assigned','Under Investigation','Pending','Rejected','Cancelled')
  AND
    V_QUAL_CONFIG_ITSM_SERVICE.MIS_3_NS = 'CAEE II'