/* Formatted on 23/04/16 20:36:54 (QP5 v5.287) */

SELECT V_CHANGE_ALL_DATA.CHANGE_ID,
       V_CHANGE_ALL_DATA.COORDINATOR_GROUP,
       V_CHANGE_ALL_DATA.COORDINATOR_GROUP_SUPP_ORG,
       V_CHANGE_ALL_DATA.COORDINATOR_DEPTGRP,
       V_CHANGE_ALL_DATA.MANAGER_GROUP,
       V_CHANGE_ALL_DATA.MANAGER_GROUP_SUPP_ORG,
       V_CHANGE_ALL_DATA.MANAGER_DEPTGRP,
       V_CHANGE_ALL_DATA.SERVICE,
       V_CHANGE_ALL_DATA.SERVICE_MAINDEPT,
       V_CHANGE_ALL_DATA.SERVICE_DEPT,
       V_CHANGE_ALL_DATA.SERVICE_DEPTGRP,
       V_CHANGE_ALL_DATA.PROD_CAT3,
       V_CHANGE_ALL_DATA.SUMMARY,
       V_CHANGE_ALL_DATA.CLASS,
       V_CHANGE_ALL_DATA.IMPACT,
       V_CHANGE_ALL_DATA.URGENCY,
       V_CHANGE_ALL_DATA.PRIORITY,
       V_CHANGE_ALL_DATA.RISK_LEVEL,
       V_CHANGE_ALL_DATA.STATUS,
       V_CHANGE_ALL_DATA.SUBMIT_DATE,
       V_CHANGE_ALL_DATA.TARGET_DATE,
       V_CHANGE_ALL_DATA.REQUESTED_START_DATE,
       V_CHANGE_ALL_DATA.SCHEDULED_START_DATE,
       TO_CHAR (V_CHANGE_ALL_DATA."SCHEDULED_START_DATE", 'YYYY_MM')
          AS "SHEDULED_START_DATE_YEAR_MONTH",
       V_CHANGE_ALL_DATA.SCHEDULED_END_DATE,
       V_CHANGE_ALL_DATA.EARLIEST_START_DATE,
       V_CHANGE_ALL_DATA.ACTUAL_START_DATE,
       V_CHANGE_ALL_DATA.ACTUAL_END_DATE,
       V_CHANGE_ALL_DATA.SCHEDULED_DATE,
       V_CHANGE_ALL_DATA.COMPLETED_DATE,
       V_CHANGE_ALL_DATA.CLOSED_DATE,
       V_CHANGE_ALL_DATA.LEADTIME_ACHIEVEMENT,
       V_CHANGE_ALL_DATA.LEADTIME_SECONDS,
       V_CHANGE_ALL_DATA.ONTIME_ACHIEVEMENT_FLAG,
       V_CHANGE_ALL_DATA.OVERDUE_FLAG,
       V_CHANGE_ALL_DATA.RELATED_CI_FLAG,
       V_CHANGE_ALL_DATA.IMPACTED_AREA_FLAG,
       V_CHANGE_ALL_DATA.RELATED_TASK_FLAG,
       CASE
          WHEN (V_CHANGE_ALL_DATA."NOTES" IS NULL) THEN 'not filled'
          ELSE 'filled'
       END
          AS "NOTES_FILLED_FLAG",
       TO_CHAR (SUBMIT_DATE, 'Month') AS Month,
       TO_CHAR (SUBMIT_DATE, 'YYYY') AS Year
  FROM V_CHANGE_ALL_DATA
       LEFT JOIN V_QUAL_CONFIG_ITSM_SERVICE
          ON V_CHANGE_ALL_DATA."SERVICE" =
                V_QUAL_CONFIG_ITSM_SERVICE."ITSM_SERVICE"
 WHERE V_QUAL_CONFIG_ITSM_SERVICE.MIS_3_NS = 'CAEE II'
 and V_CHANGE_ALL_DATA.NOTES IS NULL
 and V_CHANGE_ALL_DATA.COORDINATOR_GROUP in ('ab:ibm','ao-caee:ibm')
 and V_CHANGE_ALL_DATA.STATUS in ('Draft','Implementation in Progress','Pending','Planning in Progress','Request For Authorization','Request For Change','Scheduled','Scheduled For Approval','Scheduled For Review')
 ;
